#!/bin/bash

# Check Supabase Timezone and Cron Schedule
# This script helps verify the timezone settings and cron schedule

echo "🌍 Checking Supabase Timezone and Cron Schedule..."
echo ""

echo "📋 To check your Supabase timezone and cron schedule:"
echo ""
echo "1. Go to your Supabase Dashboard > SQL Editor"
echo "2. Run these queries:"
echo ""
echo "   -- Check current timezone"
echo "   SELECT current_setting('timezone');"
echo ""
echo "   -- Check current time in different timezones"
echo "   SELECT "
echo "     NOW() as utc_time,"
echo "     NOW() AT TIME ZONE 'UTC' as utc_timezone,"
echo "     NOW() AT TIME ZONE 'America/Vancouver' as pst_time,"
echo "     NOW() AT TIME ZONE 'America/Los_Angeles' as pst_pdt_time;"
echo ""
echo "   -- Check scheduled cron jobs"
echo "   SELECT * FROM cron.job;"
echo ""
echo "   -- Check cron job run history"
echo "   SELECT * FROM cron.job_run_details ORDER BY start_time DESC LIMIT 10;"
echo ""
echo "📅 Current Cron Schedule: 0 20 * * 5"
echo "   This means: At 20:00 UTC (8:00 PM UTC) on Friday"
echo ""
echo "🕐 Timezone Conversion:"
echo "   - 20:00 UTC = 12:00 PM PST (Pacific Standard Time)"
echo "   - 20:00 UTC = 1:00 PM PDT (Pacific Daylight Time)"
echo ""
echo "⚠️  Note: PST/PDT changes with daylight saving time"
echo "   - PST (Winter): UTC-8 (20:00 UTC = 12:00 PM PST)"
echo "   - PDT (Summer): UTC-7 (20:00 UTC = 1:00 PM PDT)"
echo ""
echo "🔧 If you need to adjust the schedule:"
echo "   -- For 12:00 PM PST (Winter): 0 20 * * 5"
echo "   -- For 12:00 PM PDT (Summer): 0 19 * * 5"
echo "   -- For 12:00 PM PST year-round: 0 20 * * 5 (current setting)"
