#!/bin/bash

echo "🧪 Testing Weekly Report Automation..."
echo ""

echo "📋 This script will help you test the weekly report automation."
echo "   You'll need to run these commands in your Supabase Dashboard > SQL Editor"
echo ""

echo "1️⃣ First, check if the cron job is set up correctly:"
echo "   SELECT * FROM cron.job WHERE jobname LIKE '%weekly%';"
echo ""

echo "2️⃣ Check recent cron job execution history:"
echo "   SELECT * FROM cron.job_run_details WHERE command LIKE '%weekly%' ORDER BY start_time DESC LIMIT 5;"
echo ""

echo "3️⃣ Check existing weekly reports:"
echo "   SELECT id, week_start, week_end, status, generated_at, error FROM weekly_reports ORDER BY generated_at DESC LIMIT 5;"
echo ""

echo "4️⃣ Test the automation manually:"
echo "   SELECT trigger_weekly_report_now();"
echo ""

echo "5️⃣ Check the result of the manual test:"
echo "   SELECT id, week_start, week_end, status, generated_at, error FROM weekly_reports ORDER BY generated_at DESC LIMIT 1;"
echo ""

echo "6️⃣ Check what week should have been generated last Friday:"
echo "   WITH last_friday AS ("
echo "     SELECT CASE "
echo "       WHEN EXTRACT(DOW FROM CURRENT_DATE) = 5 THEN CURRENT_DATE"
echo "       WHEN EXTRACT(DOW FROM CURRENT_DATE) = 6 THEN CURRENT_DATE - INTERVAL '1 day'"
echo "       WHEN EXTRACT(DOW FROM CURRENT_DATE) = 0 THEN CURRENT_DATE - INTERVAL '2 days'"
echo "       ELSE CURRENT_DATE - INTERVAL '1 week' + (5 - EXTRACT(DOW FROM CURRENT_DATE))::int"
echo "     END as last_friday_date"
echo "   )"
echo "   SELECT "
echo "     last_friday_date,"
echo "     date_trunc('week', last_friday_date)::date as week_start,"
echo "     (date_trunc('week', last_friday_date) + INTERVAL '6 days')::date as week_end"
echo "   FROM last_friday;"
echo ""

echo "7️⃣ Check if a report exists for last Friday's week:"
echo "   WITH last_friday AS ("
echo "     SELECT CASE "
echo "       WHEN EXTRACT(DOW FROM CURRENT_DATE) = 5 THEN CURRENT_DATE"
echo "       WHEN EXTRACT(DOW FROM CURRENT_DATE) = 6 THEN CURRENT_DATE - INTERVAL '1 day'"
echo "       WHEN EXTRACT(DOW FROM CURRENT_DATE) = 0 THEN CURRENT_DATE - INTERVAL '2 days'"
echo "       ELSE CURRENT_DATE - INTERVAL '1 week' + (5 - EXTRACT(DOW FROM CURRENT_DATE))::int"
echo "     END as last_friday_date"
echo "   )"
echo "   SELECT "
echo "     CASE WHEN EXISTS ("
echo "       SELECT 1 FROM weekly_reports "
echo "       WHERE week_start = date_trunc('week', last_friday_date)::date "
echo "       AND week_end = (date_trunc('week', last_friday_date) + INTERVAL '6 days')::date"
echo "     ) THEN 'Report EXISTS for last Friday''s week'"
echo "     ELSE 'Report MISSING for last Friday''s week'"
echo "     END as report_status"
echo "   FROM last_friday;"
echo ""

echo "📅 Current Schedule Information:"
echo "   - Cron Expression: 0 20 * * 5 (Every Friday at 20:00 UTC)"
echo "   - Local Time: 12:00 PM PST (1:00 PM PDT during daylight saving time)"
echo "   - Next Run: This Friday at 12:00 PM PST"
echo ""

echo "🔧 If you find issues:"
echo "   1. If cron job doesn't exist, the migration failed"
echo "   2. If cron job exists but has errors, check the return_message in job_run_details"
echo "   3. If no report exists for last Friday's week, the automation failed"
echo "   4. If manual test fails, there's an issue with the function or data"
echo ""

echo "✅ Run these queries in your Supabase Dashboard to diagnose the issue!"
